version: '3'
# version-3 has commenting :)
services: 
   mysql-test-db:
      #container_name: jsql-test-db-1
      image: mysql:8.0.13
      environment:
          MYSQL_DATABASE: testDB
          MYSQL_ROOT_PASSWORD: towhid@123
      expose:
          - 3306
   spring-jsql-service:
         #container_name: spring-jsql-1
         build:
            context: .
            dockerfile: Dockerfile
         environment:
            BASE_FILENAME: microservice.properties
            DATABASE_URL: mysql-test-db
            com.itsoul.lab.api.gateway: http://itsoul-itracker-api.org
         ports:
            - 8084:8080
         depends_on: 
            - mysql-test-db
